Changes to test configurations options and externals for parsing
NOAA-GFDL/NDSL pull request #53
Opened 2024-06-07 18:27 UTC by fmalatino

**Description**
Conditional statement in `stencils/testing/test_translate.py` changed to check for `compute` passed via the `--grid` pytest option.

Switched conditional statement in `ndsl/stencils/testing/conftest.py` to check for option of `cubed-sphere` selection

Made `mysign` parameter of `fill_corners_dgrid_defn` an external variable

Resolves Issue [52](https://github.com/NOAA-GFDL/NDSL/issues/52)

**How Has This Been Tested?**
Tested in `pyFV3` and `pySHiELD` translate tests github workflow.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included

2024-06-11 18:19 UTC, bensonr submitted a review, later dismissed

2024-06-11 18:19 UTC, bensonr commented on ndsl/stencils/testing/conftest.py
> +    if (MPI.COMM_WORLD.Get_size() > 1) and (topology_mode == "cubed-sphere"):
This change will definitely make a big difference!!

2024-06-13 14:00 UTC, FlorianDeconinck requested changes
Revert the `mysign`
Revert the `gt4py` and `dace` changes it's out of PR

2024-06-13 14:00 UTC, FlorianDeconinck commented on ndsl/dsl/stencil.py
> +            "mysign": -1.0,
This is too aggressive as a fix. The `axis_offsets` function shouldn't carry the mysign issue.

2024-06-13 14:00 UTC, FlorianDeconinck commented on ndsl/stencils/corners.py
> +    from __externals__ import i_end, i_start, j_end, j_start, mysign
Pass it as a default externals or directly a scalar, since _never_ changes in our code

2024-06-13 14:00 UTC, FlorianDeconinck commented on ndsl/stencils/testing/conftest.py
> +    if (MPI.COMM_WORLD.Get_size() > 1) and (topology_mode == "cubed-sphere"):
This was a bug I introduce in the PR right before

2024-06-17 13:55 UTC, FlorianDeconinck approved these changes
LGTM.

This will have downstream effect on `pyFV3` due to the external change. The `mysign` change has been approved by me. It's only used like this and therefore should be explicit .

2024-06-18 14:42 UTC, oelbert approved these changes
LGTM. Can you put an issue in PyFV3 to propagate the change to `fill_corners_dgrid_defn` there once this is merged?

2024-06-18 14:47 UTC, fmalatino commented
> LGTM. Can you put an issue in PyFV3 to propagate the change to `fill_corners_dgrid_defn` there once this is merged?

@oelbert those changes should be currently in [PR 23](https://github.com/NOAA-GFDL/PyFV3/pull/23), which is still in draft as it is dependent on this PR.

2024-06-20 14:51 UTC, merged