Option to merge blocks in serialized data
NOAA-GFDL/NDSL pull request #68
Opened 2024-08-30 18:37 UTC by oelbert

**Description**
This PR adds an option to merge data into a single savepoint when the Fortran code has been horizontally blocked. Data is reshaped into nx by ny in order to fit directly into the correct quantity size.

**How Has This Been Tested?**
This code has been used to postprocess test data for pySHiELD development

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included

2024-08-30 18:39 UTC, fmalatino submitted a review, later dismissed

2024-09-03 13:04 UTC, FlorianDeconinck requested changes
- Remove changed to `gt4py` and `dace`
- Run Lint

2024-09-03 13:04 UTC, FlorianDeconinck commented on ndsl/stencils/testing/serialbox_to_netcdf.py
> +                        #else:
Remove the code below.
Add a print above (maybe only printed once per execution) to feedback that we are doing dubious copies

2024-09-03 13:04 UTC, FlorianDeconinck commented on ndsl/stencils/testing/serialbox_to_netcdf.py
> +    parser.add_argument(
We are working on an extension to Serialbox that will deal with this Fortran side.

2024-09-03 14:33 UTC, oelbert commented on ndsl/stencils/testing/serialbox_to_netcdf.py
> +    parser.add_argument(
That would be nice. I thought about doing that but figured this would just be faster and not require regenerating the data

2024-09-03 15:30 UTC, fmalatino approved these changes
lgtm

2024-09-03 18:52 UTC, FlorianDeconinck approved these changes
This is the way

_epic music plays_

2024-09-03 18:52 UTC, merged